# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    product_reader_service:
      class: StreamDataBundle\Service\FileReaderService
      arguments: ['%dir_data_name%','%products_data_name%']
    transaction_reader_service:
      class: StreamDataBundle\Service\FileReaderService
      arguments: ['%dir_data_name%','%transactions_data_name%']
    currency_exchange_rate_service:
      class: CurrencyBundle\Service\StaticCurrencyExchangeRateService
    currency_converter_service:
      class: CurrencyBundle\Service\CurrencyConverterService
      arguments: ["@currency_exchange_rate_service"]
    output_printer_service:
      class: ReportBundle\Service\OutputStdPrinterService
    transaction_merchant_service:
      class: MerchantBundle\Service\MerchantService
      arguments: ["@product_reader_service", "@transaction_reader_service"]
    report_service:
      class: ReportBundle\Service\ReportService
      arguments: ["@output_printer_service", "@transaction_merchant_service"]

